services:
  celerity:
    container_name: celerity
    image: celerity
    # image: ghcr.io/thaddeuskkr/celerity:latest
    build: .
    env_file:
      - .env
    environment:
      TZ: Asia/Singapore
      LAVALINK_URL: lavalink:6969

  lavalink:
    container_name: lavalink
    image: ghcr.io/lavalink-devs/lavalink:v4
    restart: on-failure
    ports:
      - 6969:6969
    volumes:
      - ./application.yml:/opt/Lavalink/application.yml:ro