services:
  celerity:
    container_name: celerity
    # image: celerity
    image: ghcr.io/thaddeuskkr/celerity:latest
    restart: unless-stopped
    build: .
    env_file:
      - .env
    environment:
      TZ: Asia/Singapore